# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-19 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('real_name', models.CharField(max_length=30)),
                ('tz', models.CharField(max_length=40)),
                ('activity_periods', models.CharField(max_length=200)),
            ],
        ),
    ]
