# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-19 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('throttlelabapp', '0002_auto_20200620_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_periods',
            field=models.CharField(max_length=350),
        ),
    ]
