# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-20 01:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('throttlelabapp', '0003_auto_20200620_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_periods',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
