# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-20 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('throttlelabapp', '0004_auto_20200620_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_periods',
            field=models.CharField(max_length=500),
        ),
    ]
